---
apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: staging
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
        "auths": {
            "https://index.docker.io/v1/": {
                "auth": "dckr_pat_knif0QIuqO8pknUTUySsVVGfw2E"
            }
        }
    }
