---
apiVersion: v1
kind: Secret
metadata:
  name: lesson-158-private
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: ssh://git@github.com/antonputra/lesson-158-private.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACD1QlWRWy7JtHWX2+PLgmhaLpBDVWyJOLazF3zBYgqCHAAAAJjalXZ12pV2
    dQAAAAtzc2gtZWQyNTUxOQAAACD1QlWRWy7JtHWX2+PLgmhaLpBDVWyJOLazF3zBYgqCHA
    AAAEAps6/flqECqtmEPTW8c0mfDKgaXuACoZtsEqzNKqk6QvVCVZFbLsm0dZfb48uCaFou
    kENVbIk4trMXfMFiCoIcAAAAFWFyZ29jZEBhbnRvbnB1dHJhLmNvbQ==
    -----END OPENSSH PRIVATE KEY-----
  insecure: "false"
  enableLfs: "true"
