---
apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: prometheus
spec:
  type: LoadBalancer
  ports:
    - name: service
      port: 9090
      protocol: TCP
  selector:
    app.kubernetes.io/name: prometheus
