---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: dev
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          imagePullPolicy: Always
          image: aputra/myapp-lesson158:latest
          args:
            - -interval
            - "1000"
          resources:
            requests:
              memory: 64Mi
              cpu: 250m
            limits:
              memory: 64Mi
              cpu: 250m
      tolerations:
        - key: fluentd
          operator: Exists
          effect: NoSchedule
        - key: fluentbit
          operator: Exists
          effect: NoSchedule
        - key: logstash
          operator: Exists
          effect: NoSchedule
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: service
                    operator: In
                    values:
                      - myapp
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - myapp
              topologyKey: "kubernetes.io/hostname"
