---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-fluentd
  namespace: dev
spec:
  replicas: 20
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: myapp-fluentd
  template:
    metadata:
      labels:
        app: myapp-fluentd
    spec:
      containers:
        - name: myapp-fluentd
          imagePullPolicy: Always
          image: aputra/myapp-lesson158:latest
          args:
            - -interval
            - "10"
          resources:
            requests:
              memory: 64Mi
              cpu: 50m
            limits:
              memory: 64Mi
              cpu: 50m
      tolerations:
        - key: fluentd
          operator: Exists
          effect: NoSchedule
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: service
                    operator: In
                    values:
                      - myapp
